plugins {
    id 'base'
}

tasks.named('build') {
    dependsOn ':LifestealCore:build'
    dependsOn ':LifestealScoreboard:build'
    dependsOn ':LifestealSouls:build'
    dependsOn ':LifestealSoulShop:build'
    dependsOn ':LifestealSpawn:build'
}

tasks.named('clean') {
    dependsOn ':LifestealCore:clean'
    dependsOn ':LifestealScoreboard:clean'
    dependsOn ':LifestealSouls:clean'
    dependsOn ':LifestealSoulShop:clean'
    dependsOn ':LifestealSpawn:clean'
}
